#ifndef CYGONCE_PKGCONF_ATHTTPD_H
#define CYGONCE_PKGCONF_ATHTTPD_H
/*
 * File <pkgconf/athttpd.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGNUM_NET_ATHTTPD_THREADOPT_PRIORITY 16
#define CYGNUM_NET_ATHTTPD_THREADOPT_PRIORITY_16
#define CYGNUM_NET_ATHTTPD_THREADOPT_STACKSIZE 8192
#define CYGNUM_NET_ATHTTPD_THREADOPT_STACKSIZE_8192
#define CYGNUM_NET_ATHTTPD_SERVEROPT_PORT 80
#define CYGNUM_NET_ATHTTPD_SERVEROPT_PORT_80
#define CYGDAT_NET_ATHTTPD_SERVEROPT_SERVERID "eCos Embedded Web Server"
#define CYGNUM_ATHTTPD_SERVER_BUFFER_SIZE 4096
#define CYGNUM_ATHTTPD_SERVER_BUFFER_SIZE_4096
#define CYGNUM_ATHTTPD_SERVER_MAX_POST 1000000
#define CYGNUM_ATHTTPD_SERVER_MAX_POST_1000000
#define CYGDAT_NET_ATHTTPD_SERVEROPT_ROOTDIR "/"
#define CYGDAT_NET_ATHTTPD_SERVEROPT_ERRORDIR "errors/"
#define CYGDAT_NET_ATHTTPD_DEFAULT_MIME_TYPE "text/plain"
#define CYGDAT_NET_ATHTTPD_ALTERNATE_HOME "/index.html"
#define CYGOPT_NET_ATHTTPD_USE_FS 1
#define CYGOPT_NET_ATHTTPD_USE_AUTH 1
#define CYGOPT_NET_ATHTTPD_DOCUMENT_EXPIRATION_TIME 0
#define CYGOPT_NET_ATHTTPD_DOCUMENT_EXPIRATION_TIME_0
#define CYGOPT_NET_ATHTTPD_DEBUG_LEVEL 0
#define CYGOPT_NET_ATHTTPD_DEBUG_LEVEL_0

#endif
