#ifndef CYGONCE_PKGCONF_HAL_ARM_IMMENSTAR_H
#define CYGONCE_PKGCONF_HAL_ARM_IMMENSTAR_H
/*
 * File <pkgconf/hal_arm_immenstar.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */


#define HAL_PLATFORM_BOARD  "IMST"
#define HAL_PLATFORM_EXTRA  ""

#define CYGINT_DEVS_FLASH_INTEL_28FXXX_REQUIRED 1
#define CYGINT_DEVS_FLASH_INTEL_28FXXX_REQUIRED_1
#define CYGPKG_HAL_ARM_IMST_ARM9 1
#define HAL_PLATFORM_CPU    "ARM 9"
#define CYG_HAL_ARM_ENDIAN LITTLE_ENDIAN
#define CYG_HAL_ARM_ENDIAN_LITTLE_ENDIAN
#define CYG_HAL_UART IMST
#define CYG_HAL_UART_IMST
#define IMST_UART 1
#define CYG_HAL_ARM_IMST_DEV_FREQ 62500000
#define CYG_HAL_ARM_IMST_DEV_FREQ_62500000
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_DEFAULT 0
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_DEFAULT_0
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_BAUD 115200
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_BAUD_115200
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL_BAUD 115200
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL_BAUD_115200
#define CYGHWR_HAL_ARM_IMST_DIAG_LEDS 1
#define CYGNUM_HAL_VIRTUAL_VECTOR_COMM_CHANNELS 2
#define CYGNUM_HAL_VIRTUAL_VECTOR_COMM_CHANNELS_2
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL 0
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL_0
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL 0
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_0
#define CYGNUM_HAL_RTC_CONSTANTS 1
#define CYGNUM_HAL_RTC_NUMERATOR 1000000000
#define CYGNUM_HAL_RTC_NUMERATOR_1000000000
#define CYGNUM_HAL_RTC_DENOMINATOR 100
#define CYGNUM_HAL_RTC_DENOMINATOR_100
#define CYGNUM_HAL_RTC_PERIOD 9765
#define CYGNUM_HAL_RTC_PERIOD_9765
#define CYGBLD_GLOBAL_OPTIONS 1

#endif
