#ifndef CYGONCE_PKGCONF_NET_LWIP_H
#define CYGONCE_PKGCONF_NET_LWIP_H
/*
 * File <pkgconf/net_lwip.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGPKG_LWIP_STACK current
#define CYGPKG_LWIP_STACK_current
#define CYGPKG_NET_STACK 1
#define CYGPKG_NET_STACK_1
#define CYGPKG_NET_STACK_INET 1
#define CYGPKG_NET_STACK_INET_1
#define CYGPKG_NET_STACK_INET6 0
#define CYGPKG_NET_STACK_INET6_0
#define CYGDAT_LWIP_SERV_ADDR 192,168,1,100
#define CYGDAT_LWIP_MY_ADDR 192,168,1,1
#define CYGDAT_LWIP_NETMASK 255,255,255,0
#define CYGNUM_LWIP_MEM_ALIGNMENT 4
#define CYGNUM_LWIP_MEM_ALIGNMENT_4
#define CYGNUM_LWIP_MEM_SIZE 4000
#define CYGNUM_LWIP_MEM_SIZE_4000
#define CYGNUM_LWIP_MEMP_NUM_PBUF 16
#define CYGNUM_LWIP_MEMP_NUM_PBUF_16
#define CYGNUM_LWIP_MEMP_NUM_UDP_PCB 8
#define CYGNUM_LWIP_MEMP_NUM_UDP_PCB_8
#define CYGNUM_LWIP_MEMP_NUM_TCP_PCB 20
#define CYGNUM_LWIP_MEMP_NUM_TCP_PCB_20
#define CYGNUM_LWIP_MEMP_NUM_TCP_PCB_LISTEN 16
#define CYGNUM_LWIP_MEMP_NUM_TCP_PCB_LISTEN_16
#define CYGNUM_LWIP_MEMP_NUM_TCP_SEG 16
#define CYGNUM_LWIP_MEMP_NUM_TCP_SEG_16
#define CYGNUM_LWIP_MEMP_NUM_SYS_TIMEOUT 4
#define CYGNUM_LWIP_MEMP_NUM_SYS_TIMEOUT_4
#define CYGNUM_LWIP_MEMP_NUM_NETBUF 4
#define CYGNUM_LWIP_MEMP_NUM_NETBUF_4
#define CYGNUM_LWIP_MEMP_NUM_NETCONN 40
#define CYGNUM_LWIP_MEMP_NUM_NETCONN_40
#define CYGNUM_LWIP_MEMP_NUM_APIMSG 32
#define CYGNUM_LWIP_MEMP_NUM_APIMSG_32
#define CYGNUM_LWIP_MEMP_NUM_TCPIP_MSG 32
#define CYGNUM_LWIP_MEMP_NUM_TCPIP_MSG_32
#define CYGNUM_LWIP_PBUF_POOL_SIZE 60
#define CYGNUM_LWIP_PBUF_POOL_SIZE_60
#define CYGNUM_LWIP_PBUF_POOL_BUFSIZE 1024
#define CYGNUM_LWIP_PBUF_POOL_BUFSIZE_1024
#define CYGNUM_LWIP_PBUF_LINK_HLEN 16
#define CYGNUM_LWIP_PBUF_LINK_HLEN_16
#define CYGPKG_LWIP_TCP 1
#define CYGNUM_LWIP_TCP_TTL 255
#define CYGNUM_LWIP_TCP_TTL_255
#define CYGIMP_LWIP_TCP_QUEUE_OOSEQ 1
#define CYGNUM_LWIP_TCP_MSS 2048
#define CYGNUM_LWIP_TCP_MSS_2048
#define CYGNUM_LWIP_TCP_SND_BUF 2048
#define CYGNUM_LWIP_TCP_SND_BUF_2048
#define CYGNUM_LWIP_TCP_SND_QUEUELEN 16
#define CYGNUM_LWIP_TCP_SND_QUEUELEN_16
#define CYGNUM_LWIP_TCP_WND 4096
#define CYGNUM_LWIP_TCP_WND_4096
#define CYGNUM_LWIP_TCP_MAXRTX 12
#define CYGNUM_LWIP_TCP_MAXRTX_12
#define CYGNUM_LWIP_TCP_SYNMAXRTX 4
#define CYGNUM_LWIP_TCP_SYNMAXRTX_4
#define CYGNUM_LWIP_ARP_TABLE_SIZE 10
#define CYGNUM_LWIP_ARP_TABLE_SIZE_10
#define CYGFUN_LWIP_IP_FORWARD 1
#define CYGFUN_LWIP_IP_OPTIONS 1
#define CYGFUN_LWIP_IP_FRAG 1
#define CYGFUN_LWIP_IP_REASS 1
#define CYGNUM_LWIP_ICMP_TTL 255
#define CYGNUM_LWIP_ICMP_TTL_255
#define CYGFUN_LWIP_LOOPIF 1
#define CYGPKG_LWIP_ETH 1
#define CYGNUM_LWIP_ETH_THREAD_PRIORITY 11
#define CYGNUM_LWIP_ETH_THREAD_PRIORITY_11
#define CYGNUM_LWIP_NETWORK_THREAD_PRIORITY 11
#define CYGNUM_LWIP_NETWORK_THREAD_PRIORITY_11
#define CYGPKG_LWIP_UDP 1
#define CYGNUM_LWIP_UDP_TTL 255
#define CYGNUM_LWIP_UDP_TTL_255
#define CYGFUN_LWIP_RAW 1
#define CYGFUN_LWIP_COMPAT_SOCKETS 1
#define CYGNUM_LWIP_VARMEMPOOL_SIZE 4096
#define CYGNUM_LWIP_VARMEMPOOL_SIZE_4096
#define CYGNUM_LWIP_APP_THREADS 1
#define CYGNUM_LWIP_APP_THREADS_1
#define CYGNUM_LWIP_THREAD_STACK_SIZE 8192
#define CYGNUM_LWIP_THREAD_STACK_SIZE_8192

#endif
