#ifndef CYGONCE_PKGCONF_SYSTEM_H
#define CYGONCE_PKGCONF_SYSTEM_H
/*
 * File <pkgconf/system.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGNUM_VERSION_CURRENT 0x7fffff00
#define CYGPKG_HAL_ARM current
#define CYGPKG_HAL_ARM_current
#define CYGNUM_HAL_ARM_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_HAL_ARM_VERSION_MINOR -1
#define CYGNUM_HAL_ARM_VERSION_RELEASE -1
#define CYGPKG_HAL_ARM_IMST v2_0
#define CYGPKG_HAL_ARM_IMST_v2_0
#define CYGNUM_HAL_ARM_IMST_VERSION_MAJOR 2
#define CYGNUM_HAL_ARM_IMST_VERSION_MINOR 0
#define CYGNUM_HAL_ARM_IMST_VERSION_RELEASE -1
#define CYGBLD_HAL_TARGET_H   <pkgconf/hal_arm.h>
#define CYGBLD_HAL_PLATFORM_H <pkgconf/hal_arm_immenstar.h>
#define IMST_USE_CACHE 1
#define CYG_HAL_ARM LITTLE_ENDIAN
#define CYG_HAL_ARM_LITTLE_ENDIAN
#define IROS_VT 1
#define IMST_MIN_RAM_SIZE 2048
#define IMST_MIN_RAM_SIZE_2048
#define IMST_RAM_ORIGIN 0x0
#define IMST_RAM_ORIGIN_0x0
#define IMST_RAM_APP_START 0x20000
#define IMST_RAM_APP_START_0x20000
#define IMST_RAM_APP_LEN 0x1fe0000
#define IMST_RAM_APP_LEN_0x1fe0000
#define IMST_RAM_LEN 0x10000
#define IMST_RAM_LEN_0x10000
#define IMST_RAM_EXT_LEN 0x120000
#define IMST_RAM_EXT_LEN_0x120000
#define IMST_RAM_EXT_START 0xe0000
#define IMST_RAM_EXT_START_0xe0000
#define IMST_ROM_ORIGIN 0x30030000
#define IMST_ROM_ORIGIN_0x30030000
#define IMST_ROM_LEN 0x40000
#define IMST_ROM_LEN_0x40000
#define IMST_DEBUG_BUF_ORIG 0x0D400000
#define IMST_DEBUG_BUF_ORIG_0x0D400000
#define IMST_DEBUG_BUF_LEN 4096
#define IMST_DEBUG_BUF_LEN_4096
#define APP_BOOT_PARAMETERS_SIZE 32
#define APP_BOOT_PARAMETERS_SIZE_32
#define IMST_NUM_OF_UARTS 1
#define IMST_NUM_OF_UARTS_1
#define CYG_HAL_UART IMST
#define CYG_HAL_UART_IMST
#define IMST_UART 1
#define IMST_PLAT LYNX
#define IMST_PLAT_LYNX
#define CYG_HAL_ARM_IMST ONU_A
#define CYG_HAL_ARM_IMST_ONU_A
#define CYG_HAL_ARM_IMST_ONU 1
#define CYG_HAL_ARM_IMST_ASIC 1
#define CYG_HAL_ARM_IMST_DEV_FREQ 62500000
#define CYG_HAL_ARM_IMST_DEV_FREQ_62500000
#define CYG_HAL_STARTUP RAM
#define CYG_HAL_STARTUP_RAM
#define CYGHWR_MEMORY_LAYOUT_LDI <pkgconf/mlt_arm_imst_ram.ldi>
#define CYGHWR_MEMORY_LAYOUT_H <pkgconf/mlt_arm_imst_ram.h>
#define IMST_PARALLEL_FLASH INTEL_28F320
#define IMST_PARALLEL_FLASH_INTEL_28F320
#define CYGPKG_HAL current
#define CYGPKG_HAL_current
#define CYGNUM_HAL_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_HAL_VERSION_MINOR -1
#define CYGNUM_HAL_VERSION_RELEASE -1
#define CYGPKG_IO current
#define CYGPKG_IO_current
#define CYGNUM_IO_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_IO_VERSION_MINOR -1
#define CYGNUM_IO_VERSION_RELEASE -1
#define CYGPKG_INFRA current
#define CYGPKG_INFRA_current
#define CYGNUM_INFRA_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_INFRA_VERSION_MINOR -1
#define CYGNUM_INFRA_VERSION_RELEASE -1
#define CYGPKG_KERNEL current
#define CYGPKG_KERNEL_current
#define CYGNUM_KERNEL_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_KERNEL_VERSION_MINOR -1
#define CYGNUM_KERNEL_VERSION_RELEASE -1
#define CYGPKG_MEMALLOC current
#define CYGPKG_MEMALLOC_current
#define CYGNUM_MEMALLOC_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_MEMALLOC_VERSION_MINOR -1
#define CYGNUM_MEMALLOC_VERSION_RELEASE -1
#define CYGPKG_ERROR current
#define CYGPKG_ERROR_current
#define CYGNUM_ERROR_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_ERROR_VERSION_MINOR -1
#define CYGNUM_ERROR_VERSION_RELEASE -1
#define CYGPKG_ISOINFRA current
#define CYGPKG_ISOINFRA_current
#define CYGNUM_ISOINFRA_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_ISOINFRA_VERSION_MINOR -1
#define CYGNUM_ISOINFRA_VERSION_RELEASE -1
#define CYGPKG_POSIX current
#define CYGPKG_POSIX_current
#define CYGNUM_POSIX_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_POSIX_VERSION_MINOR -1
#define CYGNUM_POSIX_VERSION_RELEASE -1
#define CYGPKG_IO_FILEIO current
#define CYGPKG_IO_FILEIO_current
#define CYGNUM_IO_FILEIO_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_IO_FILEIO_VERSION_MINOR -1
#define CYGNUM_IO_FILEIO_VERSION_RELEASE -1
#define CYGPKG_LIBC current
#define CYGPKG_LIBC_current
#define CYGNUM_LIBC_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_LIBC_VERSION_MINOR -1
#define CYGNUM_LIBC_VERSION_RELEASE -1
#define CYGPKG_LIBC_SETJMP current
#define CYGPKG_LIBC_SETJMP_current
#define CYGNUM_LIBC_SETJMP_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_LIBC_SETJMP_VERSION_MINOR -1
#define CYGNUM_LIBC_SETJMP_VERSION_RELEASE -1
#define CYGPKG_LIBC_STRING current
#define CYGPKG_LIBC_STRING_current
#define CYGNUM_LIBC_STRING_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_LIBC_STRING_VERSION_MINOR -1
#define CYGNUM_LIBC_STRING_VERSION_RELEASE -1
#define CYGPKG_LIBC_STARTUP current
#define CYGPKG_LIBC_STARTUP_current
#define CYGNUM_LIBC_STARTUP_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_LIBC_STARTUP_VERSION_MINOR -1
#define CYGNUM_LIBC_STARTUP_VERSION_RELEASE -1
#define CYGPKG_HAL_ARM_ARM9 current
#define CYGPKG_HAL_ARM_ARM9_current
#define CYGNUM_HAL_ARM_ARM9_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_HAL_ARM_ARM9_VERSION_MINOR -1
#define CYGNUM_HAL_ARM_ARM9_VERSION_RELEASE -1
#define CYGBLD_HAL_ARM_VAR_IO_H
#define CYGPKG_HAL_ARM_ARM9_ARM926EJ 1
#define CYGPKG_LIBC_I18N current
#define CYGPKG_LIBC_I18N_current
#define CYGNUM_LIBC_I18N_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_LIBC_I18N_VERSION_MINOR -1
#define CYGNUM_LIBC_I18N_VERSION_RELEASE -1
#define CYGPKG_LIBC_STDIO current
#define CYGPKG_LIBC_STDIO_current
#define CYGNUM_LIBC_STDIO_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_LIBC_STDIO_VERSION_MINOR -1
#define CYGNUM_LIBC_STDIO_VERSION_RELEASE -1
#define CYGPKG_LIBC_STDLIB current
#define CYGPKG_LIBC_STDLIB_current
#define CYGNUM_LIBC_STDLIB_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_LIBC_STDLIB_VERSION_MINOR -1
#define CYGNUM_LIBC_STDLIB_VERSION_RELEASE -1
#define CYGPKG_LIBC_TIME current
#define CYGPKG_LIBC_TIME_current
#define CYGNUM_LIBC_TIME_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_LIBC_TIME_VERSION_MINOR -1
#define CYGNUM_LIBC_TIME_VERSION_RELEASE -1
#define CYGPKG_IO_WALLCLOCK current
#define CYGPKG_IO_WALLCLOCK_current
#define CYGNUM_IO_WALLCLOCK_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_IO_WALLCLOCK_VERSION_MINOR -1
#define CYGNUM_IO_WALLCLOCK_VERSION_RELEASE -1
#define CYGPKG_LIBM current
#define CYGPKG_LIBM_current
#define CYGNUM_LIBM_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_LIBM_VERSION_MINOR -1
#define CYGNUM_LIBM_VERSION_RELEASE -1
#define CYGPKG_NET_LWIP current
#define CYGPKG_NET_LWIP_current
#define CYGNUM_NET_LWIP_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_NET_LWIP_VERSION_MINOR -1
#define CYGNUM_NET_LWIP_VERSION_RELEASE -1
#define CYGPKG_LWIP_IPV4_SUPPORT 1
#define CYGPKG_IO_ETH_DRIVERS current
#define CYGPKG_IO_ETH_DRIVERS_current
#define CYGNUM_IO_ETH_DRIVERS_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_IO_ETH_DRIVERS_VERSION_MINOR -1
#define CYGNUM_IO_ETH_DRIVERS_VERSION_RELEASE -1
#define CYGPKG_ATHTTPD current
#define CYGPKG_ATHTTPD_current
#define CYGNUM_ATHTTPD_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_ATHTTPD_VERSION_MINOR -1
#define CYGNUM_ATHTTPD_VERSION_RELEASE -1
#define CYGPKG_CRC current
#define CYGPKG_CRC_current
#define CYGNUM_CRC_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_CRC_VERSION_MINOR -1
#define CYGNUM_CRC_VERSION_RELEASE -1
#define CYGPKG_CPULOAD current
#define CYGPKG_CPULOAD_current
#define CYGNUM_CPULOAD_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_CPULOAD_VERSION_MINOR -1
#define CYGNUM_CPULOAD_VERSION_RELEASE -1
#define CYGPKG_FS_RAM current
#define CYGPKG_FS_RAM_current
#define CYGNUM_FS_RAM_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_FS_RAM_VERSION_MINOR -1
#define CYGNUM_FS_RAM_VERSION_RELEASE -1
#define CYGPKG_FS_JFFS2 current
#define CYGPKG_FS_JFFS2_current
#define CYGNUM_FS_JFFS2_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_FS_JFFS2_VERSION_MINOR -1
#define CYGNUM_FS_JFFS2_VERSION_RELEASE -1
#define CYGPKG_IO_FLASH current
#define CYGPKG_IO_FLASH_current
#define CYGNUM_IO_FLASH_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_IO_FLASH_VERSION_MINOR -1
#define CYGNUM_IO_FLASH_VERSION_RELEASE -1
#define CYGPKG_COMPRESS_ZLIB current
#define CYGPKG_COMPRESS_ZLIB_current
#define CYGNUM_COMPRESS_ZLIB_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_COMPRESS_ZLIB_VERSION_MINOR -1
#define CYGNUM_COMPRESS_ZLIB_VERSION_RELEASE -1
#define CYGPKG_LINUX_COMPAT current
#define CYGPKG_LINUX_COMPAT_current
#define CYGNUM_LINUX_COMPAT_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_LINUX_COMPAT_VERSION_MINOR -1
#define CYGNUM_LINUX_COMPAT_VERSION_RELEASE -1
#define CYGPKG_DEVS_FLASH_INTEL_28FXXX current
#define CYGPKG_DEVS_FLASH_INTEL_28FXXX_current
#define CYGNUM_DEVS_FLASH_INTEL_28FXXX_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_DEVS_FLASH_INTEL_28FXXX_VERSION_MINOR -1
#define CYGNUM_DEVS_FLASH_INTEL_28FXXX_VERSION_RELEASE -1

#endif
